steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/brainactivit/empathica-kunde:$SHORT_SHA', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/brainactivit/empathica-kunde:$SHORT_SHA']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'empathica-kunde', '--image', 'eu.gcr.io/brainactivit/empathica-kunde:$SHORT_SHA', '--region', 'europe-west1','--platform', 'managed', '--quiet']
images:
- eu.gcr.io/brainactivit/empathica-kunde:$SHORT_SHA