steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/brainactivit/empathica-kunde:$SHORT_SHA', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/brainactivit/empathica-kunde:$SHORT_SHA']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'empathica-kunde-gcptest', '--image', 'eu.gcr.io/brainactivit/empathica-kunde:$SHORT_SHA', '--region', 'europe-west1','--platform', 'managed', '--quiet', '--update-env-vars', 'SPRING_PROFILES_ACTIVE=gcptest']
images:
- eu.gcr.io/brainactivit/empathica-kunde:$SHORT_SHA